common: use uint32_t instead of u_int32_t
This fixes the build error with libmusl:

	error: unknown type name ‘u_int32_t’; did you mean ‘uint32_t’?

Signed-off-by: Heiko Thiery <heiko.thiery@gmail.com>
[bb@ti.com: modified commit message]
Signed-off-by: Bryan Brattlof <bb@ti.com>